theme: jekyll-theme-cayman

# Site settings
title: Tany's blog
SEOTitle: Tany's blog
header-img: img/post-bg-universe.jpg
email: tanyanghzsd@gmail.com
description: ""
keyword: ""
url: "http://tanyanghzsd.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/tanyanghzsd/tanyanghzsd.github.io.git" # you code repository

Sidebar settings
sidebar: false                           # whether or not using Sidebar.
sidebar-about-description: "NLP Engineer"
sidebar-avatar: /img/avatar_m.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`